task :default => :tu

desc "Pruebas unitarias de la clase Racional"
task :tu do
  sh "ruby -I. test/racional_test_v2.rb"
end

desc "Ejecutar solo las pruebas simples"
task :simple do
  sh "ruby -I. test/racional_test_v2.rb -n /simple/"
end